#include <string.h>

const char SOLID_BOX = 219;
const char SPACE = ' ';
const char END_STR = '\0';

const char ZERO[5][4] = {
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SOLID_BOX, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
};

const char ONE[5][4] = {
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
};

const char TWO[5][4] = {
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SOLID_BOX, SPACE, SPACE, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
};

const char THREE[5][4] = {
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
};

const char FOUR[5][4] = {
    {SOLID_BOX, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
};

const char FIVE[5][4] = {
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SOLID_BOX, SPACE, SPACE, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
};

const char SIX[5][4] = {
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SOLID_BOX, SPACE, SPACE, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SOLID_BOX, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
};

const char SEVEN[5][4] = {
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
};

const char EIGHT[5][4] = {
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SOLID_BOX, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SOLID_BOX, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
};

const char NINE[5][4] = {
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SOLID_BOX, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
    {SPACE, SPACE, SOLID_BOX, END_STR},
    {SOLID_BOX, SOLID_BOX, SOLID_BOX, END_STR},
};

const char DDOT[5][4] = {
    {SPACE, SPACE, SPACE, END_STR},
    {SPACE, SOLID_BOX, SPACE, END_STR},
    {SPACE, SPACE, SPACE, END_STR},
    {SPACE, SOLID_BOX, SPACE, END_STR},
    {SPACE, SPACE, SPACE, END_STR},
};

